#%Module1.0

set compilernames [regexp -all -inline {\S+} [regsub -all {/\S*} "ROLLCOMPILER" ""]]
set mpinames [regexp -all -inline {\S+} [regsub -all {/\S*} "ROLLMPI" ""]]

module-whatis "p3dfft"
module-whatis "Version: VERSION"
module-whatis "Description: p3dfft"
module-whatis "Compiler: $compilernames"
module-whatis "MPI Flavors: $mpinames"

# Figure out the applicable compiler--either the one whose module was loaded
# when this modulefile was loaded or the one with the most-recently-loaded
# module.  Report an error if neither applies.
if [info exists env(P3DFFTHOME)] {
  foreach {compiler} $compilernames {
    if {[string first "/$compiler" $::env(P3DFFTHOME)] >= 0} {
      break
    }
  }
} elseif [info exists env(LOADEDMODULES)] {
  foreach {module} [split $::env(LOADEDMODULES) :] {
    set module [lindex [split $module /] 0]
    if {[regexp [format {%s(/|\s|$)} $module] $compilernames]} {
      set compiler $module
    }
  }
}
if { ! [info exists compiler] } {
  puts stderr "Need to load a compiler module first"
  exit 1
}

# Figure out the applicable mpi--either the one whose module was loaded
# when this modulefile was loaded or the one with the most-recently-loaded
# module.  Default to first element of ROLLMPI if neither applies.
set mpi [lindex $mpinames 0]
if [info exists env(P3DFFTHOME)] {
  foreach {mpi} $mpinames {
    if {[string first "/$mpi" $::env(P3DFFTHOME)] >= 0} {
      break
    }
  }
} elseif [info exists env(LOADEDMODULES)] {
  foreach {module} [split $::env(LOADEDMODULES) :] {
    set module [lindex [split $module /] 0]
    if {[regexp [format {%s(/|\s|$)} $module] $mpinames]} {
      set mpi $module
    }
  }
}

set p3dfftHome /opt/p3dfft/$compiler/$mpi
setenv P3DFFTHOME $p3dfftHome
prepend-path PATH $p3dfftHome/bin
prepend-path LD_LIBRARY_PATH $p3dfftHome/lib
