#%Module1.0
module-whatis "p3dfft"
module-whatis "Version: VERSION"
module-whatis "Description: p3dfft"
module-whatis "Compiler: COMPILERNAME"
module-whatis "MPI Flavors: ROLLMPI"
# Look for MPI flavor in LOADEDMODULES. If no MPI module is loaded, default to
# first element in ROLLMPI.
set mpi [lindex [split "ROLLMPI" "/ "] 0]
foreach {module} [split $::env(LOADEDMODULES) :] {
  set module [lindex [split $module /] 0]
  if {[regexp [format {%s(/|\s|$)} $module] "ROLLMPI"]} {
    set mpi $module
  }
}
set p3dfftHome /opt/p3dfft/COMPILERNAME/$mpi
setenv P3DFFTHOME $p3dfftHome
prepend-path PATH $p3dfftHome/bin
prepend-path LD_LIBRARY_PATH $p3dfftHome/lib
